#插件版本，涉及到自动更新config.yml内容，一般情况下请勿改动
version: ${version}
#是否开启版本更新检查
check_update: true
#是否移除所有的原版配方
remove_all_vanilla_recipe: false
#含有此Lore的物品不能参与合成，可以使用正则表达式
lore_cannot_craft: '.*不可用于合成.*'
#是否将全部由插件定义的原版配方都为玩家在配方书中解锁，默认为true
#也可以在每个配方的配置文件里定义是否解锁，配方配置文件中的优先级高于此处的优先级
all_recipe_unlocked: false
#是否启用插件铁砧配方
enable_anvil_recipe: true