version: ${version}
checkUpdate: true
remove_all_vanilla_recipe: false

messages:
  #使用命令的一些消息
  commands:
    noPerm: '&c你没有使用该命令的权限'
    noArgs: '&c请输入子命令以执行'
    nullArg: '&c不存在的子命令'
    reload: '&a插件重载成功'
    reloadConfig: '&a配置文件重载成功'
    version: '&a插件版本: %version%'
    missingParam: '&c缺少参数，请检查输入是否正确'
    playerOnly: '&c此命令只能玩家使用!'
    import: '&a导入成功'
    notExist: '&c配方不存在'
    removed: '&a配方已移除'
  #插件加载过程中的一些消息
  load:
    finish: '&a插件加载完毕'
    vaultSuccess: '&a发现经济插件,已挂钩'
    vaultFailed: '&c未发现经济插件,金钱检查将不会生效'
    pointsSuccess: '&a发现点券插件,已挂钩'
    pointsFailed: '&c未发现点券插件,点券检查将不会生效'
    itemsAdderSuccess: '&a发现ItemsAdder,已挂钩'
    itemsAdderFailed: '&c未发现ItemsAdder'
  update:
    newVersion: '&8[&3Oasis&bRecipe&8] &a检测到有新版本发布, 请及时更新到新版本'