name: Craftorithm
version: '${version}'
description: Craft recipes management system
main: com.github.yufiriamazenta.craftorithm.Craftorithm
api-version: 1.13
load: POSTWORLD
softdepend: [ Vault, LuckPerms, PlayerPoints, PlaceholderAPI, ItemsAdder, Oraxen, MythicMobs ]
authors: [ YufiriaMazenta ]
folia-supported: true
website: https://github.com/YufiriaMazenta/Craftorithm
permissions:
  craftorithm.command:
    description: Plugin command main permissions
  craftorithm.recipe_list.manager:
    default: op