name: OasisRecipe
version: ${version}
main: top.oasismc.oasisrecipe.OasisRecipe
api-version: 1.13
load: POSTWORLD
softdepend: [ Vault, LuckPerms, PlayerPoints, PlaceholderAPI ]
authors: [ YufiriaMazenta ]
website: https://github.com/YufiriaMazenta/OasisRecipe
commands:
  oasisrecipe:
    aliases:
      - or
    permission: oasis.command.oasisrecipe
permissions:
  oasis.command.oasisrecipe:
    default: op