name: Craftorithm
version: ${version}
main: com.github.yufiriamazenta.craftorithm.Craftorithm
api-version: 1.13
load: POSTWORLD
depend: [ ParettiaLib ]
softdepend: [ Vault, LuckPerms, PlayerPoints, PlaceholderAPI ]
authors: [ YufiriaMazenta ]
folia-supported: true
website: https://github.com/YufiriaMazenta/Craftorithm
commands:
  craftorithm:
    aliases:
      - craft
    permission: craftorithm.command.main
permissions:
  craftorithm.command.main:
    default: op
  craftorithm.anvil.color:
    default: op