name: Craftorithm
version: ${version}
main: me.yufiria.craftorithm.Craftorithm
api-version: 1.13
load: POSTWORLD
softdepend: [ Vault, LuckPerms, PlayerPoints, PlaceholderAPI ]
authors: [ YufiriaMazenta ]
website: https://github.com/YufiriaMazenta/Craftorithm
commands:
  craftorithm:
    aliases:
      - craft
    permission: craftorithm.command.main
permissions:
  craftorithm.command.main:
    default: op