name: OasisRecipe
version: ${version}
main: top.oasismc.oasisrecipe.OasisRecipe
api-version: 1.13
load: POSTWORLD
softdepend: [ Vault, LuckPerms, PlayerPoints, ItemsAdder, PlaceholderAPI, MythicMobs, Oraxen ]
authors: [ ChiyodaXiaoYi ]
commands:
  oasisrecipe:
    aliases:
      - or
    permission: oasis.command.oasisrecipe
permissions:
  oasis.command.oasisrecipe:
    default: op