template_shaped: #合成配方的名字,只能使用英文小写字母,".", "_", "/"和数字
  #合成表的合成物品，使用results:开头可以调用results.yml文件定义的物品, 使用ItemsAdder:开头可以调用ItemsAdder物品
  result: 'results:result1'
  #合成表的类型
  type: 'shaped'
  #合成表的合成物品，使用items:开头可以调用item.yml文件定义的物品, 使用ItemsAdder:开头可以调用ItemsAdder物品
  items:
    - 'items:item1 items:item1 items:item1'
    - 'AIR AIR AIR'
    - 'AIR AIR AIR'
  #设置合成的权限检测
  conditions:
    - 'perm oasis.recipe.test'
    - '&money >= *10.0'
    - '&points >= *10'
    - '&!level >= *10'
    - '&chunk slime'
    - '&effect BAD_OMEN >= *1'
    - '&random >= 0.5'
  #配方合成之后执行的动作
  actions:
    - 'take-level 10'
    - 'take-money 10.0'
    - 'take-points 10'
    - 'command me hello'

template_shapeless:
  result: 'results:result2'
  type: 'shapeless'
  #合成表所需物品,顺序无关,只取前9个物品
  items:
    - 'items:item2'

template_cooking:
  result: 'results:result1'
  #烧炼类配方,有furnace(熔炉),campfire("营火"),blasting("高炉"),smoking("烟熏炉")四类
  type: 'furnace'
  #熔炉的烧炼物品,只取第一个物品
  items:
    - 'items:item1'
  #熔炉配方的特有属性,设定烧炼后给予多少经验值
  exp: 0
  #熔炉配方的特有属性,设定配方烧炼的时间
  time: 10

template_smithing:
  result: 'DIAMOND_SWORD'
  type: 'smithing'
  #锻造台合成配方,第一行为第一个槽,第二行为第二个槽
  items:
    - 'IRON_SWORD'
    - 'items:item1'

template_stoneCutting:
  result: 'results:result1'
  #切石机配方
  type: 'stoneCutting'
  #切石机的原料,只取第一个物品
  items:
    - 'items:item1'
template_random_furnace:
  #在此处配置每个结果的概率, 若概率总和超过1, 则超过1部分的概率将无效
  #若概率总和小于1, 则小于1的部分将烧炼出空物品
  result:
    - 'results:result1 0.5'
    - 'results:result2 0.4'
    - 'STONE 0.1'
  #furnace(熔炉),blasting("高炉"),smoking("烟熏炉")均支持随机配方
  #随机配方只支持1.18+
  type: 'random_furnace'
  items:
    - 'COMMAND_BLOCK'
  exp: 0
  time: 10
template_multiple:
  type: 'shapeless'
  result: 'STONE'
  multiple: true
  items:
    a:
      - 'BEDROCK'
    b:
      - 'COMMAND_BLOCK'
    c:
      - 'STRUCTURE_BLOCK'