name: Craftorithm
version: ${version}
main: com.github.yufiriamazenta.craftorithm.Craftorithm
api-version: 1.17
load: POSTWORLD
softdepend: [ Vault, LuckPerms, PlayerPoints, PlaceholderAPI, ItemsAdder, Oraxen, MythicMobs ]
authors: [ YufiriaMazenta ]
folia-supported: true
website: https://github.com/YufiriaMazenta/Craftorithm
permissions:
  craftorithm.command:
    description: Plugin command main permissions